__version__ = "0.6.13"

from .opponent_history import install_owner_history_patch
from .roster_strategy import install_roster_strategy_patch
from .live_roster_context import install_live_roster_context_patch
from .expert_upside_production import install_expert_upside_production_patch
from .yahoo_room_behavior import install_yahoo_room_behavior_patch
from .team_concentration import install_team_concentration_patch
from .decision_strategy import install_decision_strategy_patch
from .opponent_availability import install_opponent_availability_patch

install_owner_history_patch()
install_roster_strategy_patch()
install_live_roster_context_patch()
install_expert_upside_production_patch()
install_yahoo_room_behavior_patch()
install_team_concentration_patch()
install_decision_strategy_patch()
install_opponent_availability_patch()
