__version__ = "0.5.7"

from .opponent_history import install_owner_history_patch
from .roster_strategy import install_roster_strategy_patch
from .live_roster_context import install_live_roster_context_patch
from .expert_upside_production import install_expert_upside_production_patch

install_owner_history_patch()
install_roster_strategy_patch()
install_live_roster_context_patch()
install_expert_upside_production_patch()
